import { library } from '@fortawesome/fontawesome-svg-core';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import {
  faAward,
  faTruckFast,
  faIndustry,
  faFlag,
  faCircleCheck,
  faPaperPlane,
  faFileArrowDown,
  faPhone,
  faEnvelope,
  faUtensils,
  faAppleWhole,
  faListCheck,
  faPenRuler,
  faPrint,
  faGlobe,
  faVial,
  faBoxesStacked,
  faFilePdf,
  faCloudArrowUp,
  faLocationDot,
  faTimeline,
  faDiagramProject,
  faBars,
  faTimes,
  faChevronDown,
  faCheckCircle,
  faShoppingCart,
  faDownload,
  faExternalLinkAlt,
  faPlayCircle,
} from '@fortawesome/free-solid-svg-icons';

import {
  faFacebook,
  faLinkedin,
  faXTwitter,
  faYoutube,
  faWhatsapp,
} from '@fortawesome/free-brands-svg-icons';

// Add icons to the library
library.add(
  faAward,
  faTruckFast,
  faIndustry,
  faFlag,
  faCircleCheck,
  faPaperPlane,
  faFileArrowDown,
  faPhone,
  faEnvelope,
  faUtensils,
  faAppleWhole,
  faListCheck,
  faPenRuler,
  faPrint,
  faGlobe,
  faVial,
  faWhatsapp,
  faBoxesStacked,
  faFilePdf,
  faCloudArrowUp,
  faLocationDot,
  faTimeline,
  faDiagramProject,
  faBars,
  faTimes,
  faChevronDown,
  faCheckCircle,
  faShoppingCart,
  faDownload,
  faExternalLinkAlt,
  faPlayCircle,
  faFacebook,
  faLinkedin,
  faXTwitter,
  faYoutube
);

export { FontAwesomeIcon };
export default FontAwesomeIcon;